#!/bin/bash

# Preguntamos variables al usuario

# interfaz de red interna
for i in `cat /proc/net/dev |  grep ":" | tr -s " " | sed "s/^[ \t]*//" | cut -f1 -d":"`; do
        ip="`ifconfig ${i} | grep "inet " | tr -s " " |  sed "s/^[ \t]*//" | cut -d" " -f 2`"
        [ -z $ip ] && ip="-"
        opciones="${opciones} ${i} ${ip}"
done

############## Variable para guardar la tarjeta de la red interna ###########
DHCP_INTERFACE=`zenity --list --title="Interfaz de la red interna" --column="Interfaz" --column="Dirección actual" $opciones`

# Se podria hacer que si se ha seleccionado anteriormente una tarjeta de red en para
# la variable  DHCP_INTERFACES no apareciera la tarjeta anteriormente selccionada
############## Variable para guardar la tarjeta de la red externa ###########
EXTERNAL_INTERFACE=`zenity --list --title="Interfaz de la red EXTERNA" --column="Interfaz" --column="Dirección actual" $opciones`

# Si no se indica interfaz interna salimos con error
[ "${DHCP_INTERFACE}" == "" ] && exit -1
# Si no se indica interfaz EXTERNA salimos con error
[ "${EXTERNAL_INTERFACE}" == "" ] && exit -1

### Recuadro que nos va permitir recoguer en un array los datos que nos pase el usuario. ###
DATA=`zenity --forms --title="Configuración de red" \
   --text="Indique los siguientes valores para configurar la red interna" \
   --add-entry="Dirección IP" \
   --add-entry="Máscara de red" \
   --add-entry="DHCP:DNS para los clientes" \
   --add-entry="DCHP: Dominio para los clientes" \
   --add-entry="DCHP: IP inicial" \
   --add-entry="DCHP: IP final" \
   --add-entry="DNS Externo" \
   --add-entry="DNS Externo 2" \
   
   `   

### Variables a las que les vamos a asignar los valores del array anterior para poder aplicarlas en la configuracion ###
INTERNAL_IP=`echo ${DATA} | cut -d"|" -f "1"`
INTERNAL_MASK=`echo ${DATA} | cut -d"|" -f "2"`
DNS_SERVER=`echo ${DATA} | cut -d"|" -f "3"`
DOMAIN_NAME=`echo ${DATA} | cut -d"|" -f "4"`
RANGE_INI=`echo ${DATA} | cut -d"|" -f "5"`
RANGE_END=`echo ${DATA} | cut -d"|" -f "6"`
DNS_EXTERNAL=`echo ${DATA} | cut -d"|" -f "7"`
DNS_EXTERNALTWO=`echo ${DATA} | cut -d"|" -f "8"`

#echo "INTERNAL_IP: ${INTERNAL_IP}"
#echo "DNS_SERVER: ${DNS_SERVER}"
#echo "DOMAIN_NAME: ${DOMAIN_NAME}"
#echo "RANGE_INI: ${RANGE_INI}"
#echo "RANGE_END: ${RANGE_END}"

############ Variables extras ############
## Assignamos el nombre del equipo para utilizarlo mas tarde.
NAME_SERVER= `cat /etc/hostname | tr -s " " | cut -f 1 -d" "` 

function render_template() {
  eval "echo \"$(cat $1)\""
}

### Funcion para configurar el dnsmasq que nos permite utilizar las variables anteriores###
function generate_dnsmasq_conf {
  echo "# Generando el fichero /etc/dnsmasq/ltsp.conf"
  render_template /var/lib/ltsp-raspi-builder/dnsmasq.template > /etc/dnsmasq.d/ltsp.conf
  #render_template /tmp/dnsmasq.template > /tmp/ltsp # Para tests
}

### Funcion para configurar el netplan que nos permite utilizar las variables anteriores###
function generate_network_conf {
  echo "# Generando el fichero /etc/netplan/50-static-internal-interface.yaml "
  render_template /var/lib/ltsp-raspi-builder/50-static-internal-interface.yaml.template  > /etc/netplan/50-static-internal-interface.yaml 
  #render_template /tmp/50-static-internal-interface.yaml.template > /tmp/50-static-internal-interface.yaml # Para tests
}

function generate_dirs_dnsmasq {
#Creamos las siguientes carpetas para que no de errores al iniciar el servicio de dnsmasq 

    mkdir -p /var/lib/dnsmasq/{macs,config,hosts}
    
    #Añadimos la siguente linea al  archivo server para que el dnsmasq sepa quien es el servidor
    echo "${INTERNAL_IP} ${NAME_SERVER}.${DOMAIN_NAME}" > /var/lib/dnsmasq/hosts/server 
    #Añadimos dos dns al archivo extra-dns para que el dnsmasq no nos de error por falta de dns
    echo -e "server=${DNS_EXTERNAL} \nserver=${DNS_EXTERNALTWO}"> /var/lib/dnsmasq/config/extra-dns
    #Descomentamos la linea en resolved.conf para que no aparezcan problemas con el resolv y el dnsmasq
    sed 's/#DNSStubListener=no/DNSStubListener=no/g' /etc/systemd/resolved.conf


return 0

}

### Funcion para preparar el sistema para que nos permita añadir las siguientes lineas
# dentro del archivo /etc/environment para asi guardar las variables como globales 
# para poder utilizarlas para crear el archivo cmdline.txt para configurar el arranque de
# la raspberry y tambien para crear un script con reglas de iptbales para enrrutar los paquetes
# de la red interna con la externa.
function preparedsd {

    sed -i "/INTERNAL_IP/d" /etc/environment
    echo "INTERNAL_IP=${INTERNAL_IP}" >> /etc/environment 

    sed -i "/EXTERNAL_INTERFACE/d" /etc/environment
    echo "EXTERNAL_INTERFACE=${EXTERNAL_INTERFACE}" >> /etc/environment 

}

### Inicializacion de las variables ###
# Nos mostrara el processo en una pestaña emerguente del processo de instalacion.
(generate_dnsmasq_conf && 
 generate_network_conf && 
 echo "# Aplicando configuración de red" && 
 netplan apply &&
 echo "# Finalizado") | tee >(zenity --progress --pulsate --title "Aplicando cambios" )

# Falta afegir la resta de configuració si és necessària (pàgina 38, etc)
# I afegir les regles d'iptables

